
var searchModule=searchModule||{$searchModule:$('.m-homepage-hotelsearch,.m-homepage-hsearch'),$homepageRewardsbar:$('#homepage-rewards-bar'),$upcomingReservationSection:$(".m-upcoming-reservation"),$homepageLoginBox:$('.m-header-myaccount'),init:function(){searchModule.$moreSearchOptions=searchModule.$searchModule.find('.t-more-search-options');searchModule.$specialRatesToggle=searchModule.$searchModule.find('.toggle');searchModule.$searchCloseButton=searchModule.$searchModule.find('.js-search-close');searchModule.$specialRatesContainer=searchModule.$searchModule.find('#special-rates-search');searchModule.$corpCodeValue=$(searchModule.$specialRatesContainer).find(".search-corp");searchModule.$rewardPoints=searchModule.$searchModule.find('.js-points');if($(searchModule.$rewardPoints).is(':checked')){searchModule.$corpCodeValue.val('');}
if(typeof searchModule.$corpCodeValue.val()!='undefined'&&searchModule.$corpCodeValue.val()!==""){searchModule.openSearchForm(true);$('#other').prop("checked",true);}
searchModule.$searchModule.on('click','.js-find-container',function(e){e.preventDefault();if(!searchModule.$searchModule.hasClass("is-opened")){$('.l-overlay-right.t-bg-opacity-90').removeClass('is-hidden');searchModule.openSearchForm(true);}
else{$('.l-overlay-right.t-bg-opacity-90').addClass('is-hidden');searchModule.closeSearchForm();}
setTimeout(function(){$('#search-location').focus();},200);});searchModule.$searchModule.on('click','.js-form-close',searchModule.closeSearchForm);searchModule.$searchModule.on('click','.js-moreoptions-expander-click',searchModule.openSearchForm);searchModule.$searchModule.on('focus','.js-moreoptions-expander',searchModule.openSearchForm);searchModule.$searchModule.on('change','.search-length-of-stay, .search-state, .search-country',searchModule.openSearchForm);searchModule.$searchModule.on('click','.js-search-close a',function(e){e.preventDefault();searchModule.closeSearchForm();});},openSearchForm:function(forceOpen){if(forceOpen==true||!$('.js-moreoptions-trigger').is(':visible')){if(!searchModule.$searchModule.hasClass("is-opened")){searchModule.$moreSearchOptions.slideDown('fast').removeClass('is-hidden');searchModule.$searchCloseButton.removeClass('is-hidden');searchModule.$searchModule.addClass("is-opened");$('.l-overlay-right.t-bg-opacity-90').addClass('is-hidden');$('.l-bottom-progressive').addClass("l-bottom-prog-open");hSearchModule.reposition();}}},closeSearchForm:function(e){if($('body').hasClass('is-form-takeover')){hSearchModule.$searchModule.css('top','75%');$('body').removeClass('is-form-takeover');}
searchModule.$moreSearchOptions.slideUp('fast').addClass('is-hidden');searchModule.$searchCloseButton.addClass('is-hidden');searchModule.$searchModule.removeClass("is-opened");$('.l-overlay-right.t-bg-opacity-90').removeClass('is-hidden');$('.l-bottom-progressive').removeClass("l-bottom-prog-open");hSearchModule.reposition();}};var hSearchModule={$toggleCheckBox:$('.js-h-toggle-checkbox'),$rewardsCheckbox:$('.js-userewards-checkbox'),$specialRatesJS:$('.js-h-toggle'),$specialRatesToggleJS:$('.js-special-rates-header'),$searchLocation:$('.js-search-location'),$searchModule:$('.m-homepage-hsearch'),initReposition:function(){if(typeof Response!='undefined'&&$('body').data('responsive')==true){Response.ready(function(){hSearchModule.reposition();Response.create({prop:"width",prefix:"r",breakpoints:[0,560,864,1024],lazy:false}).crossover(function(){hSearchModule.reposition();},"width");});}},reposition:function(){var windowHeight,offHt,heroHeight,wHeight=$(window).height(),wInnerHeight=$(window).innerHeight();windowHeight=wHeight;if(wHeight>wInnerHeight){windowHeight=wInnerHeight;}
if(hSearchModule.$searchModule.hasClass("is-opened")){if((window.matchMedia&&window.matchMedia("(min-width: 864px)").matches)||(!window.matchMedia&&!Response.band(0,864))){$('body').removeClass('is-form-takeover');offHt='38%';}else{$('body').addClass('is-form-takeover');}}else{if(Response.band(0,480)){heroHeight=480;offHt='73%';}
else if(Response.band(481,1024)){heroHeight=480;offHt='73%';}
else if(Response.band(1025)){heroHeight=560;offHt='75%';}
if(windowHeight<heroHeight){offHt=(windowHeight-150)+'px';}}
hSearchModule.$searchModule.css('top',offHt);},init:function(){if(hSearchModule.$toggleCheckBox.prop("checked")){hSearchModule.$toggleCheckBox.parents().find('.l-userewards-checkmark').addClass('icon-checkmark');}
if(hSearchModule.$specialRatesJS.find("input[type='radio']:checked").val()!='none'){var specialRatesVal="";if(hSearchModule.$specialRatesJS.find("input[type='radio']:checked").val()=='other'){specialRatesVal=hSearchModule.$specialRatesJS.find("input[type='radio']:checked").parents('.l-h-toggle-opt').find('.radio-secondary-input').val();}
else{specialRatesVal=hSearchModule.$specialRatesJS.find("input[type='radio']:checked").siblings('label').html().trim();}
$('.l-h-toggle').find('.l-h-toggle-text').html(specialRatesVal);}
hSearchModule.$rewardsCheckbox.click(function(e){e.preventDefault();$(this).children('.l-userewards-checkmark').toggleClass('icon-checkmark');hSearchModule.closeToggle(hSearchModule.$specialRatesJS.siblings('#ClusterCode'),'none',true);$('.l-rooms-guests').removeClass('is-active');$('.l-rooms-guests .m-dropdown-trigger, .js-special-rates-header .m-dropdown-trigger').removeClass('dropdown-is-active');$('.js-rooms-guests-panel').hide();if(hSearchModule.$toggleCheckBox.prop("checked")){hSearchModule.$toggleCheckBox.prop("checked",false).attr("checked",false);}
else{$('.search-clusterCode-none').prop("checked",true).parents().addClass('is-checked').find('.l-h-toggle-cont .is-checked').removeClass('is-checked');hSearchModule.$toggleCheckBox.prop("checked",true).attr("checked",true);}});hSearchModule.$specialRatesToggleJS.click(function(e){if($(this).hasClass('is-active')){$(this).addClass('l-h-field');$(this).find('.m-dropdown-trigger').addClass('dropdown-is-active');$('.l-rooms-guests').removeClass('is-active');$('.l-rooms-guests .m-dropdown-trigger').removeClass('dropdown-is-active');$('.js-rooms-guests-panel').hide();}else{$(this).find('.m-dropdown-trigger').removeClass('dropdown-is-active');}});hSearchModule.$searchLocation.click(function(e){$('.l-rooms-guests, .js-special-rates-header').removeClass('is-active');$('.l-rooms-guests .m-dropdown-trigger, .js-special-rates-header .m-dropdown-trigger').removeClass('dropdown-is-active');$('.js-rooms-guests-panel, .special-rates-section').hide();});hSearchModule.$specialRatesJS.each(function(){if($(this).find('input[type="radio"]').prop("checked")){$(this).parent().addClass('is-checked');}
$(this).on('click',function(e){var $checkbox=$(this).find('input[type="radio"]');if($checkbox.length>0){e.preventDefault();$checkbox.prop("checked",true);$(this).parents().find('.l-h-toggle-cont .is-checked').removeClass('is-checked');$(this).parent().addClass('is-checked');$(this).parents().find('.l-h-toggle-cont input:text').addClass('is-hidden').hide("fast");hSearchModule.$toggleCheckBox.parents().find('.l-userewards-checkmark').removeClass('icon-checkmark');hSearchModule.$toggleCheckBox.prop("checked",false).attr("checked",false);if($checkbox.val()=="other"){if($checkbox.prop("checked")){$(this).siblings('input:text').show('fast').removeClass('is-hidden').focus();}
else{$(this).siblings('input:text').addClass('is-hidden');}}else{hSearchModule.closeToggle($checkbox,$checkbox.val());$('.search-corp').addClass('is-hidden');}}});});hSearchModule.$specialRatesJS.parents().find('.radio-secondary-input').on('blur',function(){var $checkbox=$(this).parent().find('input[type="radio"]');hSearchModule.closeToggle($checkbox,$checkbox.val());});hSearchModule.initReposition();},closeToggle:function($obj,objVal,changeWithoutToggle){var $toggleHeader=$('.l-h-toggle');var $specialRates=$('.special-rates-section')
var $toggleHeaderText=$toggleHeader.find('.l-h-toggle-text');if(objVal=="none"){$toggleHeaderText.html($toggleHeaderText.data('defaultheader'));hSearchModule.$specialRatesJS.parents('ul').find('.radio-secondary-input').val('');if(hSearchModule.$rewardsCheckbox.prop("checked",true)){$toggleHeaderText.html($toggleHeaderText.data('defaultheader'));}
if(!changeWithoutToggle){$toggleHeader.click();}else{$specialRates.hide();hSearchModule.$specialRatesToggleJS.removeClass('is-active');}}else{if(objVal=='other'){if($obj.parents('.l-h-toggle-opt').find('.radio-secondary-input').val()==''){$('.search-clusterCode-none').prop("checked",true).parents().addClass('is-checked').find('.l-h-toggle-cont .is-checked').removeClass('is-checked');$toggleHeaderText.html($toggleHeaderText.data('defaultheader'));}
else{$toggleHeaderText.html($obj.parents('.l-h-toggle-opt').find('.radio-secondary-input').val());}}
else{$toggleHeaderText.html($obj.siblings('label').html().trim());}
$toggleHeader.click();}}};(function(){searchModule.init();if(typeof(window.Modernizr)!=="undefined"&&!Modernizr.input.placeholder){searchModule.$searchModule.find("input[placeholder]").inputPlaceholder();searchModule.$homepageRewardsbar.find("input[placeholder]").inputPlaceholder();searchModule.$homepageLoginBox.find("input[placeholder]").inputPlaceholder();}
searchModule.$specialRatesToggle.each(function(){var $this=$(this);if(!$this.hasClass('is-active')){$this.find('span.t-icon').removeClass('icon-drawer-close').addClass('icon-drawer-open');$this.next('.toggle-container').hide();}else{$this.find('span.t-icon').removeClass('icon-drawer-open').addClass('icon-drawer-close');}});searchModule.$specialRatesToggle.on('click',function(e){e.preventDefault();var $this=$(this);$this.toggleClass('is-active');if($this.hasClass('is-active')){$this.find('span.t-icon').removeClass('icon-drawer-open').addClass('icon-drawer-close');}else{$this.find('span.t-icon').removeClass('icon-drawer-close').addClass('icon-drawer-open');}
$this.next('.toggle-container').slideToggle();});$('ul.navigation-links').siblings('h3').addClass('t-font-l t-font-normal l-padding-bottom-quarter  l-center-align');var hasUpcomingReservation=searchModule.$upcomingReservationSection.data('upcomingreservation');if(!hasUpcomingReservation)
{searchModule.$upcomingReservationSection.closest('.l-page-section').remove();}
searchModule.$homepageRewardsbar.find('a.analytics-click').each(function(e){var $rewardLink=$(this);if(!$rewardLink.attr('data-analytics')){if($rewardLink.attr('title')=='Forgot password?'){$rewardLink.attr('data-analytics','{"location":"MarriottRewardsBar","description":"Forgot Password"}');}
if($rewardLink.attr('title')=='Need a password?'){$rewardLink.attr('data-analytics','{"location":"MarriottRewardsBar","description":"Need Password"}');}
if($rewardLink.hasClass("js-join-now-link")){$rewardLink.attr('data-analytics','{"location":"MarriottRewardsBar","description":"Join Now"}');}}});MI.Anita.Components.Portfolio.init().build();})();var memberReservations=memberReservations||{myUpcomingReservations:{},reservationDropDowns:function(){this.myUpcomingReservations=$(".m-upcoming-reservation .js-reservation");if(typeof this.myUpcomingReservations!=="undefined"&&this.myUpcomingReservations.length>0){var $reservationActions=this.myUpcomingReservations.find(".js-reservation-action .is-drop-down");if($reservationActions.length>0){$reservationActions.find("a").click(function(e){var selection=$(this);var selectionDataValue=selection.data("value");if(typeof selectionDataValue!=="undefined"&&selectionDataValue!=null&&selectionDataValue.length>0){e.preventDefault();e.stopPropagation();switch(selectionDataValue){case"view-reservation-detail":var viewParams=selection.data("params");if(viewParams!=null&&viewParams!=""){var isResSite=viewParams.isResSite,url=viewParams.url;if(isResSite=="true"){var target=viewParams.target,resContext=viewParams.resContext,isRitz=viewParams.ritz,sHTML="";if(isRitz!="true"){sHTML=resContext+url;}else{sHTML=url;}
if(target=="new"){window.open(sHTML)}else{window.location.href=sHTML;}}else{sendto("US","default_domain",url,"3");}}
break;case"modify-reservation":var modifyParams=selection.data("params");if(modifyParams!=null&&modifyParams!=""){var isResSite=modifyParams.isResSite,url=modifyParams.url;if(isResSite=="true"){var target=modifyParams.target,resContext=modifyParams.resContext,isRitz=modifyParams.ritz,sHTML="";if(isRitz!="true"){sHTML=resContext+url;}else{sHTML=url;}
if(target=="new"){window.open(sHTML)}else{window.location.href=sHTML;}}else{sendto("US","default_domain",url,"3");}}
break;case"cancel-reservation":var cancelParams=selection.data("params");if(cancelParams!=null&&cancelParams!=""){var isResSite=cancelParams.isResSite;if(isResSite=="true"){var resContext=cancelParams.resContext,redemption=cancelParams.redemption,lastName=cancelParams.lastName,confNum=cancelParams.confNum,isRitz=cancelParams.ritz,sHTML="",sHTMLStr="";if(isRitz=="true"&&resContext!="/ritz"){sHTMLStr="/ritz";}
if(redemption==="true"){window.location.href=resContext+sHTMLStr+"/reservation/confirmCancelRedemptionRes.mi?lastName="+lastName+"&confirmationNumber="+confNum;}
else{sHTML=resContext+sHTMLStr+"/reservation/confirmCancelReservationDialog.mi?lastName="+lastName+"&confirmationNumber="+confNum+"&isRitzHotel="+isRitz;if(isRitz=="true"&&resContext!="/ritz"){windowprops="height=320,width=600,location=no,left=850,top=300,scrollbars=no,menubars=no,toolbars=no,resizable=no";window.open(sHTML,"ConfirmCancelReservation",windowprops);}else{confirmationModal.cancel(sHTML);}}}else{var url=cancelParams.url;if(url!=""){sendto("US","default_domain",url,"3");}}}
break;default:break;}}});}}},initialize:function(){this.reservationDropDowns();}};var myHomepage=myHomepage||{shutDropDowns:function(){var dropDowns=$(".is-drop-down");dropDowns.children(".t-drop-down-title").removeClass("t-drop-down-opened").find(".icon:first").removeClass("icon-triangle-up").addClass("icon-triangle-down");dropDowns.children(".t-drop-down-definition").slideUp();},dropDownOn:function(){$(".is-drop-down > dt").on("click.dropDown",function(){var dropDownTitle=$(this);var dropDownDefinition=dropDownTitle.siblings(".t-drop-down-definition");var dropDown=dropDownTitle.parent();if(dropDownDefinition.length>0){if(dropDownTitle.hasClass("t-drop-down-opened")){dropDownDefinition.slideUp();dropDownTitle.removeClass("t-drop-down-opened");dropDownTitle.find(".icon:first").removeClass("icon-triangle-up").addClass("icon-triangle-down");}else{myHomepage.shutDropDowns();dropDownDefinition.slideDown();dropDownTitle.addClass("t-drop-down-opened");dropDownTitle.find(".icon:first").removeClass("icon-triangle-down").addClass("icon-triangle-up");}}});},setDropDowns:function(){var dropDowns=$(".is-drop-down");dropDowns.children(".t-drop-down-definition").each(function(){var dropDown=$(this);var dropDownHeight=dropDown.siblings(".t-drop-down-title:first").outerHeight()+"px";dropDown.hide();dropDown.addClass("l-drop-down-definition");dropDown.css("top",dropDownHeight);});},initialize:function(){this.dropDownOn();this.shutDropDowns();this.setDropDowns();memberReservations.initialize();}};$(function(){myHomepage.initialize();$('.m-layout-6-6 .l-6-col').addClass('l-m-col-3 l-mml-col-9-split l-mml-last-col-split').removeClass('l-m-col-6 l-mml-last-col l-mml-col-9');$('.m-layout-6-6 .l-6-col:first-child').removeClass('l-m-last-col l-mml-last-col l-mml-last-col-split');$('.js-responsive-drawer').drawer({breakpoints:['SM-and-below'],afterActivate:function(e,widget){var hasTopBorder=widget.$el.data('hasTopBorder')||widget.$el.hasClass('t-border-top-lghtGry l-padding-top');if(hasTopBorder){widget.$el.data('hasTopBorder',true);widget.$el.removeClass('t-border-top-lghtGry l-padding-top');}},afterDeactivate:function(e,widget){var hasTopBorder=widget.$el.data('hasTopBorder');if(hasTopBorder){widget.$el.addClass('t-border-top-lghtGry l-padding-top');}}});$('.js-responsive-drawer-rewards').drawer({breakpoints:['M-and-below']});$('.js-responsive-carousel').carousel({breakpoints:['S-and-below'],items:{start:0},scroll:{fx:"none"},pagination:".js-responsive-carousel .is-carousel-pagination",css:{"width":"100%"}});var fixTileHeight=function(startItem,endItem){var maxHeight=0,startItem=startItem||0,endItem=endItem||4;$('.m-layout-3-3-3-3 .is-over-text.l-overlay-bottom').slice(startItem,endItem).each(function(){maxHeight=Math.max(maxHeight,$(this).children().height());}).css('height',maxHeight+16);}
if($(window).width()<=480){var $placeHolder=$('.l-responsive:not(.lt-ie9) .js-search-location')
if((shortPlaceholder=$placeHolder&&$placeHolder.data('placeholder')||null)){$placeHolder.attr('placeholder',shortPlaceholder)}}
if($(window).width()<=960){fixTileHeight(0,2);fixTileHeight(2,4);}else{fixTileHeight();}});var confirmationModal={cancel:function(URL){var closeText=msgResources.closeText||'Close';var loadingText=msgResources.loadingText||'Loading...';var mainClassStyles='m-modal t-modal-lang';$.magnificPopup.open({mainClass:mainClassStyles,items:{src:URL},type:'ajax',ajax:{settings:{dataType:'html'}},closeMarkup:'<div class="m-modal-utilities"><button class="m-modal-close mfp-close">%title% <i class="icon-close"></i></button></div>',tClose:closeText,tLoading:loadingText,callbacks:{beforeOpen:function(){this.container.attr('aria-live','assertive');},parseAjax:function(mfpResponse){var frag=$(mfpResponse.data).find('#layout-body-container');mfpResponse.data=frag;},ajaxContentAdded:function(){$('.mfp-close .icon-close, #no-confirm').on('click',function(e){e.preventDefault();$.magnificPopup.close();});}}});}}
$(function(){if($('.l-hsearch-cntnr').length>0){hSearchModule.init();}
$('#corporateCode').attr('spellcheck','false');var homepageHForm=$('.m-homepage-hsearch #find-a-hotel-form:not([x-aries])');if(homepageHForm.length){homepageHForm=new Aries.Components.SearchForm({el:homepageHForm,features:{singleFieldDates:null,clearInput:null,roomsGuests:null}});}
var homepageForm=$('.m-homepage-hotelsearch #find-a-hotel-form:not([x-aries])');if(homepageForm.length){homepageForm=new Aries.Components.SearchForm({el:homepageForm,features:{brands:null,dates:null,userRewards:null,geoLocation:null,autoComplete:null,validate:null,collapse:null,specialRates:{map:{other:".js-corp"}}}});}
var hRewardsModule={$signinBtn:$('.js-signin-btn a'),$anonymousForm:$('.js-anonymous-form'),$cancelLink:$('.js-cancel-link'),$rewardsBar:$('.js-rewards-bar'),init:function(){hRewardsModule.$signinBtn.click(function(e){e.preventDefault();hRewardsModule.$rewardsBar.animate({height:'toggle',opacity:'toggle'},700);hRewardsModule.$anonymousForm.animate({height:'toggle',opacity:'toggle'},700);});hRewardsModule.$cancelLink.click(function(e){e.preventDefault();hRewardsModule.$rewardsBar.animate({height:'toggle',opacity:'toggle'},700);hRewardsModule.$anonymousForm.animate({height:'toggle',opacity:'toggle'},700);});}}
if($('#homepage-rewards-bar').length>0){hRewardsModule.init();}});